# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160326_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='teams',
        ),
    ]
