# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160326_1918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='point',
            unique_together=set([('user', 'game')]),
        ),
    ]
